apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saga-choreography.fullname" . }}-jaeger
  labels:
    {{- include "saga-choreography.labels" . | nindent 4 }}
    app.kubernetes.io/name: jaeger
spec:
  replicas: {{ .Values.jaeger.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: jaeger
          image: "{{ .Values.jaeger.image }}:{{ .Values.jaeger.tag }}"
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          ports:
            - name: ui
              containerPort: 16686
            - name: otlp-grpc
              containerPort: 4317
          livenessProbe:
            httpGet:
              path: /
              port: ui
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: ui
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .Values.jaeger.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
