apiVersion: v1
kind: Service
metadata:
  name: {{ include "saga-choreography.fullname" . }}-jaeger
  labels:
    {{- include "saga-choreography.labels" . | nindent 4 }}
    app.kubernetes.io/name: jaeger
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: ui
      port: 16686
      targetPort: ui
      nodePort: 30686
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
