// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Saga struct {
	ID            string
	CorrelationID string
	OrderID       string
	State         string
	Item          string
	Qty           int32
	Amount        float64
	RetryCount    *int32
	StepDeadline  *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type SagaHistory struct {
	ID        int64
	SagaID    string
	FromState string
	ToState   string
	Event     *string
	CreatedAt time.Time
}
