// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sagas.sql

package db

import (
	"context"
	"time"
)

const createSaga = `-- name: CreateSaga :exec
INSERT INTO sagas (
    id,
    correlation_id,
    order_id,
    state,
    item,
    qty,
    amount,
    retry_count,
    step_deadline,
    created_at,
    updated_at
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::text,
    $5::text,
    $6::integer,
    $7::float8,
    $8::integer,
    $9::timestamptz,
    $10::timestamptz,
    $11::timestamptz
)
`

type CreateSagaParams struct {
	ID            string
	CorrelationID string
	OrderID       string
	State         string
	Item          string
	Qty           int32
	Amount        float64
	RetryCount    int32
	StepDeadline  *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateSaga(ctx context.Context, arg CreateSagaParams) error {
	_, err := q.db.Exec(ctx, createSaga,
		arg.ID,
		arg.CorrelationID,
		arg.OrderID,
		arg.State,
		arg.Item,
		arg.Qty,
		arg.Amount,
		arg.RetryCount,
		arg.StepDeadline,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSagaByCorrelationID = `-- name: DeleteSagaByCorrelationID :exec
DELETE FROM sagas
WHERE correlation_id = $1
`

func (q *Queries) DeleteSagaByCorrelationID(ctx context.Context, correlationID string) error {
	_, err := q.db.Exec(ctx, deleteSagaByCorrelationID, correlationID)
	return err
}

const getSagaByCorrelationID = `-- name: GetSagaByCorrelationID :one
SELECT
    id,
    correlation_id,
    order_id,
    state,
    item,
    qty,
    amount::float8 AS amount,
    COALESCE(retry_count, 0)::integer AS retry_count,
    step_deadline,
    created_at,
    updated_at
FROM sagas
WHERE correlation_id = $1
`

type GetSagaByCorrelationIDRow struct {
	ID            string
	CorrelationID string
	OrderID       string
	State         string
	Item          string
	Qty           int32
	Amount        float64
	RetryCount    int32
	StepDeadline  *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetSagaByCorrelationID(ctx context.Context, correlationID string) (GetSagaByCorrelationIDRow, error) {
	row := q.db.QueryRow(ctx, getSagaByCorrelationID, correlationID)
	var i GetSagaByCorrelationIDRow
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.OrderID,
		&i.State,
		&i.Item,
		&i.Qty,
		&i.Amount,
		&i.RetryCount,
		&i.StepDeadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSagaByID = `-- name: GetSagaByID :one
SELECT
    id,
    correlation_id,
    order_id,
    state,
    item,
    qty,
    amount::float8 AS amount,
    COALESCE(retry_count, 0)::integer AS retry_count,
    step_deadline,
    created_at,
    updated_at
FROM sagas
WHERE id = $1
`

type GetSagaByIDRow struct {
	ID            string
	CorrelationID string
	OrderID       string
	State         string
	Item          string
	Qty           int32
	Amount        float64
	RetryCount    int32
	StepDeadline  *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetSagaByID(ctx context.Context, id string) (GetSagaByIDRow, error) {
	row := q.db.QueryRow(ctx, getSagaByID, id)
	var i GetSagaByIDRow
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.OrderID,
		&i.State,
		&i.Item,
		&i.Qty,
		&i.Amount,
		&i.RetryCount,
		&i.StepDeadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSagas = `-- name: ListSagas :many
SELECT
    id,
    correlation_id,
    order_id,
    state,
    item,
    qty,
    amount::float8 AS amount,
    COALESCE(retry_count, 0)::integer AS retry_count,
    step_deadline,
    created_at,
    updated_at
FROM sagas
ORDER BY created_at DESC
`

type ListSagasRow struct {
	ID            string
	CorrelationID string
	OrderID       string
	State         string
	Item          string
	Qty           int32
	Amount        float64
	RetryCount    int32
	StepDeadline  *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListSagas(ctx context.Context) ([]ListSagasRow, error) {
	rows, err := q.db.Query(ctx, listSagas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSagasRow
	for rows.Next() {
		var i ListSagasRow
		if err := rows.Scan(
			&i.ID,
			&i.CorrelationID,
			&i.OrderID,
			&i.State,
			&i.Item,
			&i.Qty,
			&i.Amount,
			&i.RetryCount,
			&i.StepDeadline,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSagasByState = `-- name: ListSagasByState :many
SELECT
    id,
    correlation_id,
    order_id,
    state,
    item,
    qty,
    amount::float8 AS amount,
    COALESCE(retry_count, 0)::integer AS retry_count,
    step_deadline,
    created_at,
    updated_at
FROM sagas
WHERE state = $1::text
ORDER BY created_at DESC
`

type ListSagasByStateRow struct {
	ID            string
	CorrelationID string
	OrderID       string
	State         string
	Item          string
	Qty           int32
	Amount        float64
	RetryCount    int32
	StepDeadline  *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListSagasByState(ctx context.Context, state string) ([]ListSagasByStateRow, error) {
	rows, err := q.db.Query(ctx, listSagasByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSagasByStateRow
	for rows.Next() {
		var i ListSagasByStateRow
		if err := rows.Scan(
			&i.ID,
			&i.CorrelationID,
			&i.OrderID,
			&i.State,
			&i.Item,
			&i.Qty,
			&i.Amount,
			&i.RetryCount,
			&i.StepDeadline,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimedOutSagas = `-- name: ListTimedOutSagas :many
SELECT
    id,
    correlation_id,
    order_id,
    state,
    item,
    qty,
    amount::float8 AS amount,
    COALESCE(retry_count, 0)::integer AS retry_count,
    step_deadline,
    created_at,
    updated_at
FROM sagas
WHERE step_deadline < $1::timestamptz
  AND state = ANY($2::text[])
`

type ListTimedOutSagasParams struct {
	Now    time.Time
	States []string
}

type ListTimedOutSagasRow struct {
	ID            string
	CorrelationID string
	OrderID       string
	State         string
	Item          string
	Qty           int32
	Amount        float64
	RetryCount    int32
	StepDeadline  *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListTimedOutSagas(ctx context.Context, arg ListTimedOutSagasParams) ([]ListTimedOutSagasRow, error) {
	rows, err := q.db.Query(ctx, listTimedOutSagas, arg.Now, arg.States)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimedOutSagasRow
	for rows.Next() {
		var i ListTimedOutSagasRow
		if err := rows.Scan(
			&i.ID,
			&i.CorrelationID,
			&i.OrderID,
			&i.State,
			&i.Item,
			&i.Qty,
			&i.Amount,
			&i.RetryCount,
			&i.StepDeadline,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSaga = `-- name: UpdateSaga :execrows
UPDATE sagas
SET
    state = $1::text,
    retry_count = $2::integer,
    step_deadline = $3::timestamptz,
    updated_at = NOW()
WHERE id = $4::uuid
  AND updated_at = $5::timestamptz
`

type UpdateSagaParams struct {
	State        string
	RetryCount   int32
	StepDeadline *time.Time
	ID           string
	UpdatedAt    time.Time
}

func (q *Queries) UpdateSaga(ctx context.Context, arg UpdateSagaParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSaga,
		arg.State,
		arg.RetryCount,
		arg.StepDeadline,
		arg.ID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
