// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saga_history.sql

package db

import (
	"context"
	"time"
)

const createHistoryEntry = `-- name: CreateHistoryEntry :one
INSERT INTO saga_history (
    saga_id,
    from_state,
    to_state,
    event,
    created_at
) VALUES (
    $1::uuid,
    $2::text,
    $3::text,
    $4::text,
    $5::timestamptz
)
RETURNING id, created_at
`

type CreateHistoryEntryParams struct {
	SagaID    string
	FromState string
	ToState   string
	Event     string
	CreatedAt time.Time
}

type CreateHistoryEntryRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) CreateHistoryEntry(ctx context.Context, arg CreateHistoryEntryParams) (CreateHistoryEntryRow, error) {
	row := q.db.QueryRow(ctx, createHistoryEntry,
		arg.SagaID,
		arg.FromState,
		arg.ToState,
		arg.Event,
		arg.CreatedAt,
	)
	var i CreateHistoryEntryRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listSagaHistory = `-- name: ListSagaHistory :many
SELECT
    id,
    saga_id,
    from_state,
    to_state,
    COALESCE(event, '') AS event,
    created_at
FROM saga_history
WHERE saga_id = $1::uuid
ORDER BY created_at ASC, id ASC
`

type ListSagaHistoryRow struct {
	ID        int64
	SagaID    string
	FromState string
	ToState   string
	Event     string
	CreatedAt time.Time
}

func (q *Queries) ListSagaHistory(ctx context.Context, sagaID string) ([]ListSagaHistoryRow, error) {
	rows, err := q.db.Query(ctx, listSagaHistory, sagaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSagaHistoryRow
	for rows.Next() {
		var i ListSagaHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.SagaID,
			&i.FromState,
			&i.ToState,
			&i.Event,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
