FROM golang:1.26-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app ./cmd/...

FROM scratch
EXPOSE 8081
COPY --from=builder /app /app
ENTRYPOINT ["/app"]
