apiVersion: v1
kind: Service
metadata:
  name: {{ include "saga-orchestration.fullname" . }}-inventory-service
  labels:
    {{- include "saga-orchestration.labels" . | nindent 4 }}
    app.kubernetes.io/name: inventory-service
spec:
  selector:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.inventoryService.port }}
  type: ClusterIP
