apiVersion: v1
kind: Service
metadata:
  name: {{ include "saga-orchestration.fullname" . }}-postgres
  labels:
    {{- include "saga-orchestration.labels" . | nindent 4 }}
    app.kubernetes.io/name: postgres
spec:
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
