apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "saga-orchestration.fullname" . }}-postgres-data
  labels:
    {{- include "saga-orchestration.labels" . | nindent 4 }}
    app.kubernetes.io/name: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
